[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirect all API requests to our Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all other requests to the SPA index file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200