[build]
  command = "npm install serverless-http && node netlify/build-deploy-info.js && vite build && node netlify/build-db.js && esbuild netlify/functions/api.ts --platform=node --packages=external --bundle --format=esm --outfile=netlify/functions/api.mjs"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  
[functions.api]
  external_node_modules = ["serverless-http"]

# Redirect all API requests to our Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all other requests to the SPA index file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200